NAME=barbers

CC=gcc                                # pøekladaè jazyka C
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic  # parametry pøekladaèe

ALLFILES=barbers.c makefile        # obsah projektu

$(NAME): barbers.c
	$(CC) $(CFLAGS)  barbers.c -o barbers -lrt

